# -*- coding: utf-8 -*-
"""predict departure script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19O6BuUzC03FRnce5P4bucueubJ6z_LJp
"""

# predict_departure_model.py

import os
import subprocess
import argparse
import pandas as pd
import numpy as np
from pycaret.classification import load_model, predict_model

# Function to install a package if not already installed
def install(package):
    subprocess.check_call(['pip', 'install', package])

def main(args):
    # Install required libraries
    install('pandas')
    install('numpy')
    install('pycaret')

    # Load saved model
    model = load_model(args.model_path.replace('.pkl', ''))

    # Load new unseen data
    new_data = pd.read_csv(args.new_data_path)

    # Preprocessing - must match training pipeline logic
    important_cols = ['FL_DATE', 'AIRLINE', 'ORIGIN', 'DEST', 'CRS_DEP_TIME', 'DISTANCE']
    new_data = new_data.dropna(subset=important_cols)

    # Feature Engineering
    new_data['CRS_DEP_HOUR'] = new_data['CRS_DEP_TIME'] // 100
    new_data['CRS_DEP_MINUTE'] = new_data['CRS_DEP_TIME'] % 100
    new_data['CRS_ARR_HOUR'] = new_data['CRS_ARR_TIME'] // 100
    new_data['CRS_ARR_MINUTE'] = new_data['CRS_ARR_TIME'] % 100

    new_data['FL_DATE'] = pd.to_datetime(new_data['FL_DATE'])
    new_data['DAY_OF_WEEK'] = new_data['FL_DATE'].dt.dayofweek
    new_data['MONTH'] = new_data['FL_DATE'].dt.month
    new_data['DAY'] = new_data['FL_DATE'].dt.day

    new_data['DISTANCE_BIN'] = pd.qcut(new_data['DISTANCE'], q=5, labels=False)

    # Drop unused columns
    drop_cols = ['CRS_DEP_TIME', 'CRS_ARR_TIME', 'FL_DATE', 'DISTANCE']
    new_data.drop(columns=[col for col in drop_cols if col in new_data.columns], inplace=True)

    # Predict
    preds = predict_model(model, data=new_data)

    # Save predictions
    output = preds[['Label', 'Score']]
    output.columns = ['prediction_label', 'prediction_score']

    output_filename = 'departure_delay_predictions.csv'
    output.to_csv(output_filename, index=False)

    print(f"\u2705 Predictions saved as {output_filename}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_path', type=str, required=True)
    parser.add_argument('--new_data_path', type=str, required=True)
    args = parser.parse_args()

    main(args)